########################################################################
## Read Seurat clusters to look at cell-types based on a custom marker gene list (Fast cluster exploration)
## INPUT:
##      1) A custom Gene-marker list.
##      2) DGE list generated by Seurat
## 
## OUPUT:
##      1) A csv files with the matched markers found in each cluster. 
##
## Authors. CSC 
## Date. Feb 27th, 2024 / last md. Feb 28th
########################################################################

# load libraries
library(tidyverse)
library(dplyr)
library(data.table)
library(magrittr)

library(here)

here::here()

# Check if processed_data directory exists, if not create it
if (!dir.exists(here("processed-data/04_DiffExpr_Clustering_seurat/"))) {
    dir.create(here("processed-data/04_DiffExpr_Clustering_seurat/"))
}

# contains the different marker list 
source(here("code/functions_custom", "remote_DGE_marker_gene_lists.R"))       # Call functions to read paths

get_seurat <- function(name) {
    
    #Ex. /dcs04/lieber/lcolladotor/Habenula_R01_LIBD4270/Hb_multiome/processed-data/02_merge_seurats/seurat.combined.data_counts_PCA.rds
    sobj <- readRDS(name)
    # verification of the integration
    print(table(sobj$orig.ident))
    # S1_Hb_KDM S2_Hb_KDM
    # 8178      9816
    print(head(sobj, n=2))
    return(sobj)
    
}

#############################           Initials        ################################
############################# Pickup a Marker gene list ################################

# We have access to 3 gene markers lists:

# Erik and Top50r putative marker genes merged
markers.custom <- get_erik_and_Hb_markers_genes()          # merged lists
prefix_name <- 'all_gm'                                    # prefix to save matched markers found in the clusters
#markers.custom <- get_bukola_markers_genes_Hb()           # Bukola lists
#prefix_name <- 'erik_gm'  
#markers.custom <- get_Top50r_markers_genes_Hb()           # Top50r lists (putative Hb)
#prefix_name <- 'Top50r_gm'  

# str(markers.custom)
# List of 14
# $ neuron                   : chr [1:2] "SYT1" "SNAP25"
# $ excitatory_neuron        : chr [1:2] "SLC17A6" "SLC17A7"
# $ inhibitory_neuron        : chr [1:2] "GAD1" "GAD2"
# $ mediodorsal thalamus     : chr [1:10] "EPHA4" "PDYN" "LYPD6B" "LYPD6" ...
# $ Hb neuron specific       : chr [1:4] "POU2F2" "POU4F1" "GPR151" "CALB2"
# $ MHB neuron specific      : chr [1:3] "TAC1" "CHAT" "CHRNB4"
# $ LHB neuron specific      : chr [1:2] "HTR2C" "MMRN1"
# $ oligodendrocyte          : chr [1:2] "MOBP" "MBP"
# $ oligodendrocyte_precursor: chr [1:2] "PDGFRA" "VCAN"
# $ microglia                : chr [1:2] "C3" "CSF1R"
# $ astrocyte                : chr [1:2] "GFAP" "AQP4"
# $ Endo/CP                  : chr [1:4] "TTR" "FOLR1" "FLT1" "CLDN5"
# $ MHb_putative             : chr [1:50] "CHAT" "LINC01307" "NEUROD1" "CHRNB4" ...
# $ LHb_putative             : chr [1:50] "HTR4" "BVES" "NRP1" "HTR2C" ...


markers.custom$MHb_putative
# [1] "CHAT"       "LINC01307"  "NEUROD1"    "CHRNB4"     "LINC02143" 
# [6] "AC114321.1" "AC104170.1" "AC079760.2" "AC024610.2" "AC022382.2"
# ...

# # markers manually added for testing functions 
# new_gm <- c('MT-ND4', 'MT-ND2')
# markers.custom$MHb <- append(markers.custom$MHb, new_gm)
# markers.custom$MHb 

# set the number of top DGE rows to consider for looking gene markers in the cellranger-arc clusters
n_match_slice <- 20  
prefix_name <- paste0(prefix_name, n_match_slice, '.csv')    # all_gm20.csv



#############################  Set the DGE list to parse  ################################

## Setup some initials. We can now parse the clusters from the CCA or Harmony corrections
s_sample <- ''
count_mtx_type <- 'data_counts'
#count_mtx_type <- 'norm_counts' 
#Seurat_reduction <- 'CCA'
Seurat_reduction <- 'Harmony'

if (count_mtx_type=='data_counts') { Seurat_base_name <- 'seurat.combined.data_counts_PCA' } else { Seurat_base_name <- 'seurat.combined.norm_counts_PCA' }

## Compose Seurat object name processed before
if (Seurat_reduction=='CCA') {
  rds_name <- here('processed-data/02_merge_seurats', paste0(Seurat_base_name, '_CCA.rds'))
} else {
  rds_name <- here('processed-data/02_merge_seurats', paste0(Seurat_base_name, '_Harmony.rds'))
}
rds_name
# Ex. ~/Hb_multiome/processed-data/02_merge_seurats/seurat.combined.data_counts_PCA_CCA.rds"
# Ex. ~/seurat.combined.data_counts_PCA_Harmony.rds

## Load Seurat Integrated with cluster information
SeuratOBJ <- get_seurat(rds_name)
SeuratOBJ@reductions

# Ex. SeuratOBJ@reductions$integrated.cca
# A dimensional reduction object with key integratedcca_ 
# Number of dimensions: 50 
# Number of cells: 17994 
# Projected dimensional reduction calculated:  FALSE 
# Jackstraw run: FALSE 
# Computed using assay: RNA 

## extract cluster data
md <- SeuratOBJ@meta.data %>% as.data.table

## Apply vertical format to unique cluster with number of umis, arrenged by sample and cluster number
mdT <- md[, .N, by = c("orig.ident", "seurat_clusters")] %>%
    arrange(., orig.ident, seurat_clusters, .by_group = FALSE)
#     orig.ident seurat_clusters    N
# 1:  S1_Hb_KDM               0 1820
# 2:  S1_Hb_KDM               1 1230
# 3:  S1_Hb_KDM               2  679

df_mdT <- as.data.frame(mdT)
#View(df_mdT)
cvs_name <- paste0(Seurat_base_name, '_', Seurat_reduction, '_cluster_info.csv')
# > cvs_name
# [1] "seurat.combined.data_counts_PCA_CCA_cluster_info.csv"
write.csv(df_mdT, here('processed-data/04_DiffExpr_Clustering_seurat', cvs_name))

## extract unique clusters in ascending order
clusters <- as.integer(levels(unique(SeuratOBJ$seurat_clusters)))
# CCA: 19 clusters
# [1]  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
# Harmony: 
# [1]  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19


message('Looking gene markers for ', length(clusters), ' clusters for sample ', Seurat_base_name, ' for ', Seurat_reduction, ' reduction')



## Extract DGE genes for all clusters for the given sample

## Read path to cellranger-arc DGE clusters
path_cellranger_DGE_clust_df <- here('processed-data/03_pseudobulking/csv_files',
                                     paste0(Seurat_base_name, '_',Seurat_reduction, '_Allmarkers.csv'))
path_cellranger_DGE_clust_df     
# ~/seurat.combined.data_counts_PCA_CCA_Allmarkers.csv
seurat_clust <- as.data.frame(read.csv(path_cellranger_DGE_clust_df, header = TRUE))
head(seurat_clust, n=3)
# Seurat output from FindAllmarkers()
# p_val avg_log2FC pct.1 pct.2 p_val_adj cluster   gene
# 1     0  -1.836151 0.078 0.736         0     C_0  NPAS3
# 2     0  -1.188384 0.176 0.830         0     C_0    QKI
# 3     0  -1.678080 0.068 0.710         0     C_0 ZBTB20

## Subset columns of interest
seurat_clust_sub  <- select(seurat_clust, gene,  p_val_adj, cluster) 
head(seurat_clust_sub)
# gene p_val_adj cluster
# 1  MT-ND4         0       0
# 2  MT-ND2         0       0
# 3  MT-CYB         0       0

message('Parsing ', length(markers.custom), ' cell types for ', length(clusters) ,' clusters in sample ', Seurat_base_name, ' ', Seurat_reduction, ' reduction')
#Parsing 14 cell-types for clusters in sample S1_Hb_KDM




####### Parse the 10/20 DGE genes from GEX cluster against the marker genes list provided ####### 

#clusters <- sort(clusters)

# empty df to save cell-types matched 
all_gene_match <- setNames(data.frame(matrix(ncol = 5, nrow = 0)), c("Feature.ID", "Feature.Name", "Cluster.Adjusted.p.value", "cell-type", "cluster"))
#names(marker.custom_lsts)


# parse the clusters of the given sample
for (clust in clusters) {
    
    # Testing: clust<-0
    # Read cluster x and extract the 10 ten most relevant genes
    #Cluster_number <- paste0('Cluster.',clust,'.')
    #f <-  paste0(Cluster_number,'Adjusted.p.value')
    
    # format cluster name 
    clust <- paste0("C_", clust)
    top_DGE_clust <- seurat_clust_sub %>% 
        dplyr::arrange(clust) %>% 
        #select(c(gene, cluster)) %>%
        dplyr::filter(cluster == clust) %>%
        dplyr::filter(p_val_adj < 0.05) %>%
        slice_head(n = n_match_slice)
        # gene p_val_adj
        # 1    MT-ND4         0
        # 2    MT-ND2         0
        # 3    MT-CYB         0
        # 4    MT-ND1         0
        # 5    MT-ND3         0
    
    # Parse each gene in the top10 list against the marker gene list provided 
    if ( nrow(top_DGE_clust) > 0 ) {
        
        # get a vector wit all marker genes
        gm_lst <- as.vector(as.list(markers.custom))
        #names(gm_lst[1])
        i_pos <- 0      # reset gene-marker list position
        
        for ( gm in gm_lst ) {

            i_pos <- i_pos+1                        # to extract cell type position
            cell_type <- names(gm_lst[i_pos])       # to extract cell type name

            # Match top10genes with the marker genes for the cell-type x 
            gene_match <- top_DGE_clust %>% filter_all(any_vars(. %in% gm))
            print(gene_match)
            
            # add matched genes to a dataframe
            if ( nrow(gene_match) > 0 ) {
                # rename column to allow rbind
                #names(gene_match)[names(gene_match) == f ] <- "Cluster.Adjusted.p.value"
                names(gene_match)[names(gene_match) == clust ] <- "Cluster.Adjusted.p.value"
                gene_match['cell-type']  <- cell_type
                gene_match['cluster']  <- clust
                all_gene_match <- rbind(all_gene_match, gene_match)
            }
            
        }
        
    }
    
} 

# save the matched genes for the corresponding sample 
#all_gene_match
head(all_gene_match, n=3)
# gene p_val_adj cluster                 cell-type
# 1    MBP         0       1           oligodendrocyte
# 2 PDGFRA         0       4 oligodendrocyte_precursor
# 3   VCAN         0       4 oligodendrocyte_precursor

path_cellranger_clusters_markers <- here('processed-data/04_DiffExpr_Clustering_seurat', paste0(Seurat_base_name, '_', Seurat_reduction, '_cell_types_', prefix_name))
# ~/seurat.combined.data_counts_PCA_CCA_cell_types_all_gm20.csv
write.csv(all_gene_match, path_cellranger_clusters_markers, row.names=FALSE)

message(' Cell type identification in clusters done!')



################################################################################


library("sessioninfo")
print('Reproducibility information:')
# Last modification
Sys.time()
#"2023-04-04 12:42:26 EDT"
proc.time()
options(width = 120)
session_info()


# > library("sessioninfo")
# > print('Reproducibility information:')
# [1] "Reproducibility information:"
# > # Last modification
#     > Sys.time()
# [1] "2024-02-27 20:41:05 EST"
# > #"2023-04-04 12:42:26 EDT"
#     > proc.time()
# user   system  elapsed 
# 52.926    7.828 2838.397 
# > options(width = 120)
# > session_info()
# CRAN (R 4.3.1)
# BPCells            0.1.0      2023-10-02 [1] Github (bnprks/BPCells@ac4376d)
# cellranger         1.1.0      2016-07-27 [2] CRAN (R 4.3.1)
# cli                3.6.1      2023-03-23 [2] CRAN (R 4.3.1)
# cluster            2.1.4      2022-08-22 [3] CRAN (R 4.3.1)
# codetools          0.2-19     2023-02-01 [3] CRAN (R 4.3.1)
# colorspace         2.1-0      2023-01-23 [2] CRAN (R 4.3.1)
# cowplot            1.1.1      2020-12-30 [2] CRAN (R 4.3.1)
# data.table       * 1.14.8     2023-02-17 [2] CRAN (R 4.3.1)
# deldir             1.0-9      2023-05-17 [2] CRAN (R 4.3.1)
# digest             0.6.33     2023-07-07 [2] CRAN (R 4.3.1)
# dotCall64          1.1-1      2023-11-28 [1] CRAN (R 4.3.1)
# dplyr            * 1.1.4      2023-11-17 [1] CRAN (R 4.3.1)
# ellipsis           0.3.2      2021-04-29 [2] CRAN (R 4.3.1)
# fansi              1.0.6      2023-12-08 [1] CRAN (R 4.3.1)
# fastDummies        1.7.3      2023-07-06 [1] CRAN (R 4.3.1)
# fastmap            1.1.1      2023-02-24 [2] CRAN (R 4.3.1)
# fitdistrplus       1.1-11     2023-04-25 [1] CRAN (R 4.3.1)
# forcats          * 1.0.0      2023-01-29 [2] CRAN (R 4.3.1)
# future             1.33.0     2023-07-01 [2] CRAN (R 4.3.1)
# future.apply       1.11.1     2023-12-21 [1] CRAN (R 4.3.1)
# generics           0.1.3      2022-07-05 [2] CRAN (R 4.3.1)
# GenomeInfoDb       1.36.3     2023-09-07 [2] Bioconductor
# GenomeInfoDbData   1.2.10     2023-07-20 [2] Bioconductor
# GenomicRanges      1.52.0     2023-04-25 [2] Bioconductor
# ggplot2          * 3.5.0      2024-02-23 [1] CRAN (R 4.3.1)
# ggrepel            0.9.5      2024-01-10 [1] CRAN (R 4.3.1)
# ggridges           0.5.4      2022-09-26 [2] CRAN (R 4.3.1)
# globals            0.16.2     2022-11-21 [2] CRAN (R 4.3.1)
# glue               1.6.2      2022-02-24 [2] CRAN (R 4.3.1)
# goftest            1.2-3      2021-10-07 [1] CRAN (R 4.3.1)
# gridExtra          2.3        2017-09-09 [1] CRAN (R 4.3.1)
# gtable             0.3.4      2023-08-21 [2] CRAN (R 4.3.1)
# here             * 1.0.1      2020-12-13 [2] CRAN (R 4.3.1)
# hms                1.1.3      2023-03-21 [2] CRAN (R 4.3.1)
# htmltools          0.5.7      2023-11-03 [1] CRAN (R 4.3.1)
# htmlwidgets        1.6.2      2023-03-17 [2] CRAN (R 4.3.1)
# httpuv             1.6.14     2024-01-26 [1] CRAN (R 4.3.1)
# httr               1.4.7      2023-08-15 [2] CRAN (R 4.3.1)
# ica                1.0-3      2022-07-08 [1] CRAN (R 4.3.1)
# igraph             1.5.1      2023-08-10 [2] CRAN (R 4.3.1)
# IRanges            2.34.1     2023-06-22 [2] Bioconductor
# irlba              2.3.5.1    2022-10-03 [2] CRAN (R 4.3.1)
# jsonlite           1.8.7      2023-06-29 [2] CRAN (R 4.3.1)
# KernSmooth         2.23-22    2023-07-10 [3] CRAN (R 4.3.1)
# later              1.3.1      2023-05-02 [2] CRAN (R 4.3.1)
# lattice            0.21-8     2023-04-05 [3] CRAN (R 4.3.1)
# lazyeval           0.2.2      2019-03-15 [2] CRAN (R 4.3.1)
# leiden             0.4.3.1    2023-11-17 [1] CRAN (R 4.3.1)
# lifecycle          1.0.4      2023-11-07 [1] CRAN (R 4.3.1)
# listenv            0.9.0      2022-12-16 [2] CRAN (R 4.3.1)
# lmtest             0.9-40     2022-03-21 [2] CRAN (R 4.3.1)
# lubridate        * 1.9.3      2023-09-27 [1] CRAN (R 4.3.1)
# magrittr         * 2.0.3      2022-03-30 [2] CRAN (R 4.3.1)
# MASS               7.3-60     2023-05-04 [3] CRAN (R 4.3.1)
# Matrix             1.6-5      2024-01-11 [1] CRAN (R 4.3.1)
# matrixStats        1.2.0      2023-12-11 [1] CRAN (R 4.3.1)
# mime               0.12       2021-09-28 [2] CRAN (R 4.3.1)
# miniUI             0.1.1.1    2018-05-18 [2] CRAN (R 4.3.1)
# munsell            0.5.0      2018-06-12 [2] CRAN (R 4.3.1)
# nlme               3.1-163    2023-08-09 [3] CRAN (R 4.3.1)
# parallelly         1.36.0     2023-05-26 [2] CRAN (R 4.3.1)
# patchwork          1.1.3      2023-08-14 [2] CRAN (R 4.3.1)
# pbapply            1.7-2      2023-06-27 [2] CRAN (R 4.3.1)
# pillar             1.9.0      2023-03-22 [2] CRAN (R 4.3.1)
# pkgconfig          2.0.3      2019-09-22 [2] CRAN (R 4.3.1)
# plotly             4.10.4     2024-01-13 [1] CRAN (R 4.3.1)
# plyr               1.8.9      2023-10-02 [1] CRAN (R 4.3.1)
# png                0.1-8      2022-11-29 [1] CRAN (R 4.3.1)
# polyclip           1.10-6     2023-09-27 [1] CRAN (R 4.3.1)
# progressr          0.14.0     2023-08-10 [1] CRAN (R 4.3.1)
# promises           1.2.1      2023-08-10 [2] CRAN (R 4.3.1)
# purrr            * 1.0.2      2023-08-10 [2] CRAN (R 4.3.1)
# R6                 2.5.1      2021-08-19 [2] CRAN (R 4.3.1)
# RANN               2.6.1      2019-01-08 [2] CRAN (R 4.3.1)
# RColorBrewer       1.1-3      2022-04-03 [2] CRAN (R 4.3.1)
# Rcpp               1.0.11     2023-07-06 [2] CRAN (R 4.3.1)
# RcppAnnoy          0.0.21     2023-07-02 [2] CRAN (R 4.3.1)
# RcppHNSW           0.5.0      2023-09-19 [2] CRAN (R 4.3.1)
# RCurl              1.98-1.12  2023-03-27 [2] CRAN (R 4.3.1)
# readr            * 2.1.4      2023-02-10 [2] CRAN (R 4.3.1)
# readxl           * 1.4.3      2023-07-06 [2] CRAN (R 4.3.1)
# reshape2           1.4.4      2020-04-09 [2] CRAN (R 4.3.1)
# reticulate         1.35.0     2024-01-31 [1] CRAN (R 4.3.1)
# rlang              1.1.3      2024-01-10 [1] CRAN (R 4.3.1)
# ROCR               1.0-11     2020-05-02 [2] CRAN (R 4.3.1)
# rprojroot          2.0.4      2023-11-05 [1] CRAN (R 4.3.1)
# RSpectra           0.16-1     2022-04-24 [2] CRAN (R 4.3.1)
# Rtsne              0.16       2022-04-17 [2] CRAN (R 4.3.1)
# S4Vectors          0.38.2     2023-09-22 [1] Bioconductor
# scales             1.3.0      2023-11-28 [1] CRAN (R 4.3.1)
# scattermore        1.2        2023-06-12 [1] CRAN (R 4.3.1)
# sctransform        0.4.1      2023-10-19 [1] CRAN (R 4.3.1)
# sessioninfo      * 1.2.2      2021-12-06 [2] CRAN (R 4.3.1)
# Seurat             4.9.9.9067 2023-10-02 [1] Github (satijalab/seurat@99b9ded)
# SeuratObject       5.0.1      2023-11-17 [1] CRAN (R 4.3.1)
# shiny              1.8.0      2023-11-17 [1] CRAN (R 4.3.1)
# sp                 2.1-1      2023-10-16 [1] CRAN (R 4.3.1)
# spam               2.10-0     2023-10-23 [1] CRAN (R 4.3.1)
# spatstat.data      3.0-4      2024-01-15 [1] CRAN (R 4.3.1)
# spatstat.explore   3.2-5      2023-10-22 [1] CRAN (R 4.3.1)
# spatstat.geom      3.2-7      2023-10-20 [1] CRAN (R 4.3.1)
# spatstat.random    3.2-1      2023-10-21 [1] CRAN (R 4.3.1)
# spatstat.sparse    3.0-3      2023-10-24 [1] CRAN (R 4.3.1)
# spatstat.utils     3.0-4      2023-10-24 [1] CRAN (R 4.3.1)
# stringi            1.8.3      2023-12-11 [1] CRAN (R 4.3.1)
# stringr          * 1.5.1      2023-11-14 [1] CRAN (R 4.3.1)
# survival           3.5-7      2023-08-14 [3] CRAN (R 4.3.1)
# tensor             1.5        2012-05-05 [1] CRAN (R 4.3.1)
# tibble           * 3.2.1      2023-03-20 [2] CRAN (R 4.3.1)
# tidyr            * 1.3.0      2023-01-24 [2] CRAN (R 4.3.1)
# tidyselect         1.2.0      2022-10-10 [2] CRAN (R 4.3.1)
# tidyverse        * 2.0.0      2023-02-22 [2] CRAN (R 4.3.1)
# timechange         0.2.0      2023-01-11 [2] CRAN (R 4.3.1)
# tzdb               0.4.0      2023-05-12 [2] CRAN (R 4.3.1)
# utf8               1.2.4      2023-10-22 [1] CRAN (R 4.3.1)
# uwot               0.1.16     2023-06-29 [2] CRAN (R 4.3.1)
# vctrs              0.6.5      2023-12-01 [1] CRAN (R 4.3.1)
# viridisLite        0.4.2      2023-05-02 [2] CRAN (R 4.3.1)
# withr              3.0.0      2024-01-16 [1] CRAN (R 4.3.1)
# xtable             1.8-4      2019-04-21 [2] CRAN (R 4.3.1)
# XVector            0.40.0     2023-04-25 [2] Bioconductor
# zlibbioc           1.46.0     2023-04-25 [2] Bioconductor
# zoo                1.8-12     2023-04-13 [2] CRAN (R 4.3.1)
# 
# [1] /users/csoto/R/4.3
# [2] /jhpce/shared/community/core/conda_R/4.3/R/lib64/R/site-library
# [3] /jhpce/shared/community/core/conda_R/4.3/R/lib64/R/library