########################################################################
## Read Cell RangerARC clusters to look at cell-types based on a custom marker gene list (Fast cluster exploration)
## INPUT:
##      1) A custom Gene-marker list.
##      2) DGE list generated by Cell RangerARC. Manually define the paths to files. 
## 
## OUPUT:
##      1) A csv files with the matched markers found in each cluster. 
##
## Authors. CSC 
## Date. Jan 26th, 2024 / last md. Feb,15th, 2024 
########################################################################

# if (!require("SeuratData")) install.packages("SeuratData")
# # loupe dependencies
# if (!require("hdf5r")) install.packages("hdf5r")
# # install platform specific source package
# os <- sub("Darwin", "macOS", Sys.info()["sysname"])
# url <- paste0("https://github.com/10XGenomics/loupeR/releases/latest/download/loupeR_", os, ".tar.gz")
# install.packages(url, repos = NULL, type = "source")

# import the library
#library(loupeR)         # # convert the SeuratObject named `seurat_obj` to a Loupe file
library(ggplot2)
library(grid)
library(gridExtra)
library(SeuratData)
library(Seurat)
library(tidyverse)
library(dplyr)

#install.packages("ggridges")
#remotes::install_github("wilkelab/ggridges")
#library(ggridges)

library(here)
here::here()


# Check if processed_data directory exists, if not create it
if (!dir.exists(here("processed-data/05_DiffExpr_Clustering/"))) {
    dir.create(here("processed-data/05_DiffExpr_Clustering/"))
}

# Check if processed_data directory exists, if not create it
if (!dir.exists(here("plots/05_DiffExpr_Clustering/"))) {
    dir.create(here("plots/05_DiffExpr_Clustering/"))
}

#source(here("code/functions_custom", "remote_DGE_marker_gene_lists.R"))       # Call functions to read paths




##################################################################
###########  USE Cell RangerARC outputs with r-base code
###########  Not require projection on the data 
##################################################################


######### Select a specific set of genes to plot #########

source(here("code/functions_custom", "remote_DGE_marker_gene_lists.R"))       # Call functions to read paths
# We have access to 3 gene markers lists:

# Erik and Top50r putative marker genes merged
#markers.custom <- get_erik_and_Hb_markers_genes()          # merged lists
#prefix_name <- 'all_gm'                                    # prefix to save matched markers found in the clusters
markers.custom <- get_bukola_markers_genes_Hb()           # Bukola lists
prefix_name <- 'erik_gm'  
#markers.custom <- get_Top50r_markers_genes_Hb()           # Top50r lists (putative Hb)
#prefix_name <- 'Top50r_gm'
# str(markers.custom)
# List of 13
# $ neuron                   : chr [1:2] "SYT1" "SNAP25"
# $ excitatory_neuron        : chr [1:2] "SLC17A6" "SLC17A7"
# $ inhibitory_neuron        : chr [1:2] "GAD1" "GAD2"
# $ mediodorsal thalamus     : chr [1:11] "EPHA4" "PDYN" "LYPD6B" "LYPD6" ...
# $ Pf/PVT                   : chr [1:2] "INHBA" "NPTXR"
# $ Hb neuron specific       : chr [1:2] "POU4F1" "GPR151"
# $ MHB neuron specific      : chr [1:4] "TAC1" "CHAT" "CHRNB4" "TAC3"
# $ LHB neuron specific      : chr [1:3] "HTR2C" "MMRN1" "ANO3"
# $ oligodendrocyte          : chr [1:2] "MOBP" "MBP"
# $ oligodendrocyte_precursor: chr [1:2] "PDGFRA" "VCAN"
# $ microglia                : chr [1:2] "C3" "CSF1R"
# $ astrocyte                : chr [1:2] "GFAP" "AQP4"
# $ Endo/CP                  : chr [1:4] "TTR" "FOLR1" "FLT1" "CLDN5"


###########   Load Seurat pre-existing object from diskand get the counts from the GEX assay

seurat_name <- 'S2_Hb_KDM'

# file name to save plots
#file_dir <- here('plots/05_DiffExpr_Clustering', paste0(seurat_name,'_gene_distribution.png'))


seurat_obj <- readRDS(here('processed-data/01_preprocessing_QC', paste0(seurat_name, '.rds')))
# head(seurat_obj, n = 3)
# > head(seurat_obj, n = 3)
# orig.ident atac_peak_region_fragments atac_fragments
# AAACAGCCAAATTGCT-1  S1_Hb_KDM                        334           2229
# AAACAGCCAGCTTACA-1  S1_Hb_KDM                       2548          12449
# AAACAGCCAGGTCCTG-1  S1_Hb_KDM                       1698          11085

# View cell identities, get summary table
#table(Idents(seurat_obj))
assay <- seurat_obj[["RNA"]]
# Assay data with 36601 features for 8178 cells
# First 10 features:
#     MIR1302-2HG, FAM138A, OR4F5, AL627309.1, AL627309.3, AL627309.2,
# AL627309.5, AL627309.4, AP006222.2, AL732372.1 
typeof(assay)   #S4
## Cells and feature names
#Cells(assay)       #colnames(assay)
## feature names
#rownames(assay)    #Features(assay)

Layers(assay)
# [1] "counts" "data" 

# Get count matrix from either the old or newer formats of assay
counts <- seurat_obj[["RNA"]]$counts
#counts <- counts_matrix_from_assay(assay)   # S4, dfCMatrix
str(counts)
head(counts)
#counts@Dimnames
#counts@i


######### Extract information of clusters for the given sample. #########

path_cellranger_clusters_df <- here(paste0('processed-data/cellrangerARC/', seurat_name, '/outs/analysis/clustering/gex/graphclust'),
                                    'clusters.csv')
cellranger_clusters <- as.data.frame(read.csv(path_cellranger_clusters_df, header = TRUE))
cellr_clusters <- unique(cellranger_clusters['Cluster'])
clusters <- sort(cellr_clusters[['Cluster']])
#  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14
colnames(cellr_clusters)
#dim(cellranger_clusters)
# [1] 8178    2
#head(cellranger_clusters, 5)
#       Barcode           Cluster
# 1 AAACAGCCAAATTGCT-1       5
# 2 AAACAGCCAGCTTACA-1       7
# 3 AAACAGCCAGGTCCTG-1       5
# 4 AAACAGCCAGTTAAAG-1       1
# 5 AAACAGCCATAGACTT-1      10




######### Fetch gene counts for gene of interest, merge with clusters and plot distributions (Graph-based) from Cell RangerARC data  #########

plot_gene <- function(x) {

    # testing: x <- "AQP4"  #"GFAP", 'SYT1', 'RNASE1'
    print(x)
    # Fetch data to pull the barcodes with gene distributions for gene x
    counts_subseted <- FetchData(object = seurat_obj, vars = x, layer = "counts") # data.frame
    #colnames(counts_subseted)
    
    #an.error.occured <- FALSE
    #tryCatch( {
    
        if (!length(counts_subseted)==0) {
        
            # Assign new names to the columns of the data.frame 
            counts_subseted <- cbind(newColName = rownames(counts_subseted), counts_subseted)
            rownames(counts_subseted) <- NULL
            colnames(counts_subseted) <- c('Barcode',x) 
            # Add ident name 
            counts_subseted$ident <- seurat_name
            #print(head(counts_subseted, n=3))  
    
            # Join counts with clusters by barcode
            cellranger_counts_clusters <- counts_subseted %>%
                inner_join(cellranger_clusters) %>%
                group_by(Cluster)
            #print(head(cellranger_counts_clusters, n=3))
    
            if (!length(cellranger_counts_clusters)==0) {
                # Format data for plotting 
                cellranger_counts_clusters$Cluster <- as.character(cellranger_counts_clusters$Cluster)
                print(head(cellranger_counts_clusters))
                # # Groups:   Cluster [3]
                #       Barcode            SNAP25 ident     Cluster
                #       <chr>               <dbl> <chr>     <chr>  
                # 1 AAACAGCCAAATTGCT-1      0 S1_Hb_KDM     5      
                # 2 AAACAGCCAGCTTACA-1      0 S1_Hb_KDM     7      
                # 3 AAACAGCCAGGTCCTG-1      0 S1_Hb_KDM     5      
                
                # plot composed violin with boxplot 10-log-scaled
                p <- cellranger_counts_clusters %>%
                    mutate(Cluster = fct_reorder(Cluster, get(x))) %>%
                    mutate(Cluster = factor(Cluster, levels=c(as.character(clusters)))) %>%
                    ggplot(aes(fill=ident, y=get(x), x=Cluster)) +
                    geom_violin(aes(fill = factor(Cluster))) +
                    geom_boxplot(width=0.2, color="gray", alpha=0.5) & scale_y_log10()
                
                stitle <- paste0('Log10 Exp - ', x)
                #print(p)
                #print(stitle)
                p <- p & theme_classic() &
                    theme(legend.position = 'none', draw_quantiles = NULL,
                          axis.text.x = element_text(angle = 0, hjust = 1, size = 6),  #10
                          axis.text.y = element_text(size = 6), 
                          axis.title.y = element_blank()) &
                    theme(plot.title = element_text(size=10)) &
                    labs(title = stitle, x = 'Clusters', y ='log10(GEX)')
            }
            
        }
        
    #}
    #, error = function(e) { an.error.occured <<- TRUE } )
    #print(an.error.occured)
    
}


# #generate empty list to save plots
# myplots_Gene <- list()
# 
# # for testing
# #features <- c("AQP4", "GFAP", 'SYT1', 'RNASE1')
# #features <- c("SYT1", "SNAP25")
# myplots_Gene <- map(features, plot_gene)
# myplots_Gene[[2]]
# 
# nc <- length(myplots_Gene) / 4
# nc <- 1
# nr <- 4
# 
# 
# file_dir <- here('plots/05_DiffExpr_Clustering/', paste0(seurat_name,'_gene_distribution.pdf'))
# # Make plots wider
# #options(repr.plot.width=15, repr.plot.height=8)
# 
# # Build the grid for Gene plots
# message(paste0(' Saving Gene Distributions for Sample ', seurat_name))
# g1 <- arrangeGrob(grobs = myplots_Gene, ncol = nc, nrow=nr,
#                   top=textGrob(paste("Distributions for sample", seurat_name, ' Cell-Type:', 'celltype'),gp=gpar(fontsize=10,font=2)))
# ggsave(g1, filename = file_dir) #, width = 8.42, height = 3.09
# # Saving 8.42 x 3.09 in image



# Get the list of genes to plot from marker genes
gm_lst <- (as.list(markers.custom))
#names(gm_lst[1])
i_pos <- 0      # reset gene-marker list position

for ( gm in gm_lst ) {

    skip_to_next <- FALSE
    
    tryCatch( {
    
        # generate empty list
        myplots_Gene <- list()
        # set cell-type position to extract cell-type name
        i_pos <- i_pos+1                       
        
        # Genes to plot
        # testing:
        # gm <- c("SYT1", "SNAP25");  gm <- c("INHBA", "NPTXR")
        # gm <- dput(gm_lst[4])
        # call map to plot the gene distributions
        #myplots_Gene <- map(dput(features), plot_gene)
        myplots_Gene <- map(unlist(gm, use.names = FALSE), plot_gene)
        #myplots_Gene[[2]]
        print(paste(' Ploting ', length(myplots_Gene), ' genes'))
        
        # prepare layout to set 4 plots per page
        if ( length(myplots_Gene) < 4) { nc <- 1 } else { nc <- length(myplots_Gene) / 4 }
        nr <- 4
        
        # extract cell type name
        cell_type <- names(gm_lst[i_pos])       
        # format name properly
        cell_typef <- gsub(" ", "_", cell_type)
        cell_typef <- gsub("/", "_", cell_typef)
        # set file name
        file_dir <- here('plots/05_DiffExpr_Clustering/', paste0(seurat_name,'_GeneDist_', prefix_name,'-',cell_typef,'.pdf'))
        print(file_dir)
    
        # Build the grid for Gene plots
        message(paste0(' Saving Gene Distributions for Sample ', seurat_name, ' cell-type ', cell_type))
        g1 <- arrangeGrob(grobs = myplots_Gene, ncol = nc, nrow = nr,
                          top=textGrob(paste("Distributions for sample", seurat_name, ' Cell-Type:', cell_type), gp=gpar(fontsize=10,font=2)))
        ggsave(g1, filename = file_dir) #, width = 8.42, height = 3.09
    
    }, error = function(e) { skip_to_next <<- TRUE} )
    
    if(skip_to_next) { next }     
    
}



message(' All plots saved on: ', file_dir)


# counts_subseted <- FetchData(object = seurat_obj, vars = feature, layer = "counts")
# dim(counts_subseted)
# head(counts_subseted)   # data.frame
# colnames(counts_subseted)
# # assigning new names to the columns of the data frame 
# counts_subseted <- cbind(newColName = rownames(counts_subseted), counts_subseted)
# rownames(counts_subseted) <- NULL
# colnames(counts_subseted) <- c('Barcode',feature) 
# # add ident 
# counts_subseted$ident <- seurat_name
# 
# head(counts_subseted)  
# # Barcode AQP4     ident
# # 1 AAACAGCCAAATTGCT-1    0 S1_Hb_KDM
# # 2 AAACAGCCAGCTTACA-1    0 S1_Hb_KDM
# # 3 AAACAGCCAGGTCCTG-1    0 S1_Hb_KDM
# # 4 AAACAGCCAGTTAAAG-1    0 S1_Hb_KDM
# # 5 AAACAGCCATAGACTT-1    0 S1_Hb_KDM
# # 6 AAACATGCATCCCTCA-1    0 S1_Hb_KDM


# # Join counts with clusters by barcode
# cellranger_counts_clusters <- counts_subseted %>%
#     inner_join(cellranger_clusters) %>%
#     group_by(Cluster)
# head(cellranger_counts_clusters, n=3)
# # Barcode               AQP4 ident     Cluster
# # <chr>                 <dbl> <chr>       <int>
# # 1 AAACAGCCAAATTGCT-1     0 S1_Hb_KDM       5
# # 2 AAACAGCCAGCTTACA-1     0 S1_Hb_KDM       7
# # 3 AAACAGCCAGGTCCTG-1     0 S1_Hb_KDM       5


# # Format data for plotting 
# as.character(clusters)
# cellranger_counts_clusters
# cellranger_counts_clusters$Cluster <- as.character(cellranger_counts_clusters$Cluster)
# head(cellranger_counts_clusters)
# # # Groups:   Cluster [2]
# # Barcode             AQP4 ident     Cluster
# # <chr>              <dbl> <chr>       <int>
# # 1 AAACAGCCAAATTGCT-1     0 S1_Hb_KDM       5
# # 2 AAACAGCCAGCTTACA-1     0 S1_Hb_KDM       7
# # 3 AAACAGCCAGGTCCTG-1     0 S1_Hb_KDM       5
# 
# # plot composed violin with boxplot log-scaled
# 
# p <- cellranger_counts_clusters %>%
#     mutate(Cluster = fct_reorder(Cluster, get(feature))) %>%
#     mutate(Cluster = factor(Cluster, levels=c(as.character(clusters)))) %>%
#     ggplot(aes(fill=ident, y=get(feature), x=Cluster)) + 
#     geom_violin(aes(fill = factor(Cluster))) +
#     geom_boxplot(width=0.1, color="grey", alpha=0.2)
# 
# p & scale_y_log10() &
#     theme_classic() &
#     theme(legend.position = 'none', draw_quantiles = NULL) & 
#     labs(title = paste(seurat_name,': ',feature), x = 'Clusters', y ='log10(Gene-Expression)')



################################################################################


library("sessioninfo")
print('Reproducibility information:')
# Last modification
Sys.time()
#"2023-04-04 12:42:26 EDT"
proc.time()
options(width = 120)
session_info()

# > library("sessioninfo")
# > print('Reproducibility information:')
# [1] "Reproducibility information:"
# > # Last modification
#     > Sys.time()
# [1] "2024-02-01 16:07:11 EST"
# > #"2023-04-04 12:42:26 EDT"
#     > proc.time()
# user    system   elapsed 
# 4784.949  1085.661 20653.320 
# > options(width = 120)
# > session_info()
# 2023-05-22 [2] Bioconductor
# bit                    4.0.5      2022-11-15 [2] CRAN (R 4.3.1)
# bit64                  4.0.5      2020-08-30 [2] CRAN (R 4.3.1)
# bitops                 1.0-7      2021-04-24 [2] CRAN (R 4.3.1)
# BPCells                0.1.0      2023-10-02 [1] Github (bnprks/BPCells@ac4376d)
# cli                    3.6.1      2023-03-23 [2] CRAN (R 4.3.1)
# cluster                2.1.4      2022-08-22 [3] CRAN (R 4.3.1)
# codetools              0.2-19     2023-02-01 [3] CRAN (R 4.3.1)
# colorspace             2.1-0      2023-01-23 [2] CRAN (R 4.3.1)
# cowplot                1.1.1      2020-12-30 [2] CRAN (R 4.3.1)
# crayon                 1.5.2      2022-09-29 [2] CRAN (R 4.3.1)
# data.table             1.14.8     2023-02-17 [2] CRAN (R 4.3.1)
# DelayedArray           0.26.7     2023-07-28 [2] Bioconductor
# DelayedMatrixStats     1.22.6     2023-08-28 [2] Bioconductor
# deldir                 1.0-9      2023-05-17 [2] CRAN (R 4.3.1)
# digest                 0.6.33     2023-07-07 [2] CRAN (R 4.3.1)
# dotCall64              1.1-0      2023-10-17 [1] CRAN (R 4.3.1)
# dplyr                * 1.1.4      2023-11-17 [1] CRAN (R 4.3.1)
# dqrng                  0.3.1      2023-08-30 [2] CRAN (R 4.3.1)
# DropletUtils         * 1.20.0     2023-04-25 [2] Bioconductor
# edgeR                  3.42.4     2023-05-31 [2] Bioconductor
# ellipsis               0.3.2      2021-04-29 [2] CRAN (R 4.3.1)
# fansi                  1.0.5      2023-10-08 [1] CRAN (R 4.3.1)
# fastDummies            1.7.3      2023-07-06 [1] CRAN (R 4.3.1)
# fastmap                1.1.1      2023-02-24 [2] CRAN (R 4.3.1)
# fitdistrplus           1.1-11     2023-04-25 [1] CRAN (R 4.3.1)
# forcats              * 1.0.0      2023-01-29 [2] CRAN (R 4.3.1)
# future                 1.33.0     2023-07-01 [2] CRAN (R 4.3.1)
# future.apply           1.11.0     2023-05-21 [1] CRAN (R 4.3.1)
# generics               0.1.3      2022-07-05 [2] CRAN (R 4.3.1)
# GenomeInfoDb         * 1.36.3     2023-09-07 [2] Bioconductor
# GenomeInfoDbData       1.2.10     2023-07-20 [2] Bioconductor
# GenomicRanges        * 1.52.0     2023-04-25 [2] Bioconductor
# ggplot2              * 3.4.4      2023-10-12 [1] CRAN (R 4.3.1)
# ggrepel                0.9.4      2023-10-13 [1] CRAN (R 4.3.1)
# ggridges               0.5.4      2022-09-26 [2] CRAN (R 4.3.1)
# globals                0.16.2     2022-11-21 [2] CRAN (R 4.3.1)
# glue                   1.6.2      2022-02-24 [2] CRAN (R 4.3.1)
# goftest                1.2-3      2021-10-07 [1] CRAN (R 4.3.1)
# gridExtra              2.3        2017-09-09 [1] CRAN (R 4.3.1)
# gtable                 0.3.4      2023-08-21 [2] CRAN (R 4.3.1)
# HDF5Array              1.28.1     2023-05-01 [2] Bioconductor
# hdf5r                  1.3.8      2023-01-21 [2] CRAN (R 4.3.1)
# here                 * 1.0.1      2020-12-13 [2] CRAN (R 4.3.1)
# hms                    1.1.3      2023-03-21 [2] CRAN (R 4.3.1)
# htmltools              0.5.7      2023-11-03 [1] CRAN (R 4.3.1)
# htmlwidgets            1.6.2      2023-03-17 [2] CRAN (R 4.3.1)
# httpuv                 1.6.12     2023-10-23 [1] CRAN (R 4.3.1)
# httr                   1.4.7      2023-08-15 [2] CRAN (R 4.3.1)
# ica                    1.0-3      2022-07-08 [1] CRAN (R 4.3.1)
# igraph                 1.5.1      2023-08-10 [2] CRAN (R 4.3.1)
# IRanges              * 2.34.1     2023-06-22 [2] Bioconductor
# irlba                  2.3.5.1    2022-10-03 [2] CRAN (R 4.3.1)
# jsonlite               1.8.7      2023-06-29 [2] CRAN (R 4.3.1)
# KernSmooth             2.23-22    2023-07-10 [3] CRAN (R 4.3.1)
# later                  1.3.1      2023-05-02 [2] CRAN (R 4.3.1)
# lattice                0.21-8     2023-04-05 [3] CRAN (R 4.3.1)
# lazyeval               0.2.2      2019-03-15 [2] CRAN (R 4.3.1)
# leiden                 0.4.3      2022-09-10 [1] CRAN (R 4.3.1)
# lifecycle              1.0.4      2023-11-07 [1] CRAN (R 4.3.1)
# limma                  3.56.2     2023-06-04 [2] Bioconductor
# listenv                0.9.0      2022-12-16 [2] CRAN (R 4.3.1)
# lmtest                 0.9-40     2022-03-21 [2] CRAN (R 4.3.1)
# locfit                 1.5-9.8    2023-06-11 [2] CRAN (R 4.3.1)
# lubridate            * 1.9.3      2023-09-27 [1] CRAN (R 4.3.1)
# magrittr               2.0.3      2022-03-30 [2] CRAN (R 4.3.1)
# MASS                   7.3-60     2023-05-04 [3] CRAN (R 4.3.1)
# Matrix                 1.6-1.1    2023-09-18 [3] CRAN (R 4.3.1)
# MatrixGenerics       * 1.12.3     2023-07-30 [2] Bioconductor
# matrixStats          * 1.1.0      2023-11-07 [1] CRAN (R 4.3.1)
# mime                   0.12       2021-09-28 [2] CRAN (R 4.3.1)
# miniUI                 0.1.1.1    2018-05-18 [2] CRAN (R 4.3.1)
# munsell                0.5.0      2018-06-12 [2] CRAN (R 4.3.1)
# nlme                   3.1-163    2023-08-09 [3] CRAN (R 4.3.1)
# parallelly             1.36.0     2023-05-26 [2] CRAN (R 4.3.1)
# patchwork              1.1.3      2023-08-14 [2] CRAN (R 4.3.1)
# pbapply                1.7-2      2023-06-27 [2] CRAN (R 4.3.1)
# pillar                 1.9.0      2023-03-22 [2] CRAN (R 4.3.1)
# pkgconfig              2.0.3      2019-09-22 [2] CRAN (R 4.3.1)
# plotly                 4.10.3     2023-10-21 [1] CRAN (R 4.3.1)
# plyr                   1.8.9      2023-10-02 [1] CRAN (R 4.3.1)
# png                    0.1-8      2022-11-29 [1] CRAN (R 4.3.1)
# polyclip               1.10-6     2023-09-27 [1] CRAN (R 4.3.1)
# progressr              0.14.0     2023-08-10 [1] CRAN (R 4.3.1)
# promises               1.2.1      2023-08-10 [2] CRAN (R 4.3.1)
# purrr                * 1.0.2      2023-08-10 [2] CRAN (R 4.3.1)
# R.methodsS3            1.8.2      2022-06-13 [2] CRAN (R 4.3.1)
# R.oo                   1.25.0     2022-06-12 [2] CRAN (R 4.3.1)
# R.utils                2.12.2     2022-11-11 [2] CRAN (R 4.3.1)
# R6                     2.5.1      2021-08-19 [2] CRAN (R 4.3.1)
# RANN                   2.6.1      2019-01-08 [2] CRAN (R 4.3.1)
# RColorBrewer           1.1-3      2022-04-03 [2] CRAN (R 4.3.1)
# Rcpp                   1.0.11     2023-07-06 [2] CRAN (R 4.3.1)
# RcppAnnoy              0.0.21     2023-07-02 [2] CRAN (R 4.3.1)
# RcppHNSW               0.5.0      2023-09-19 [2] CRAN (R 4.3.1)
# RCurl                  1.98-1.12  2023-03-27 [2] CRAN (R 4.3.1)
# readr                * 2.1.4      2023-02-10 [2] CRAN (R 4.3.1)
# reshape2               1.4.4      2020-04-09 [2] CRAN (R 4.3.1)
# reticulate             1.34.0     2023-10-12 [1] CRAN (R 4.3.1)
# rhdf5                  2.44.0     2023-04-25 [2] Bioconductor
# rhdf5filters           1.12.1     2023-04-30 [2] Bioconductor
# Rhdf5lib               1.22.1     2023-09-10 [2] Bioconductor
# rlang                  1.1.2      2023-11-04 [1] CRAN (R 4.3.1)
# ROCR                   1.0-11     2020-05-02 [2] CRAN (R 4.3.1)
# rprojroot              2.0.4      2023-11-05 [1] CRAN (R 4.3.1)
# RSpectra               0.16-1     2022-04-24 [2] CRAN (R 4.3.1)
# Rtsne                  0.16       2022-04-17 [2] CRAN (R 4.3.1)
# S4Arrays               1.0.6      2023-08-30 [2] Bioconductor
# S4Vectors            * 0.38.2     2023-09-22 [1] Bioconductor
# scales                 1.2.1      2022-08-20 [2] CRAN (R 4.3.1)
# scattermore            1.2        2023-06-12 [1] CRAN (R 4.3.1)
# sctransform            0.4.1      2023-10-19 [1] CRAN (R 4.3.1)
# scuttle                1.10.2     2023-08-03 [2] Bioconductor
# sessioninfo          * 1.2.2      2021-12-06 [2] CRAN (R 4.3.1)
# Seurat               * 4.9.9.9067 2023-10-02 [1] Github (satijalab/seurat@99b9ded)
# SeuratObject         * 4.9.9.9091 2023-09-25 [1] Github (mojaveazure/seurat-object@c51dd86)
# shiny                  1.7.5.1    2023-10-14 [1] CRAN (R 4.3.1)
# SingleCellExperiment * 1.22.0     2023-04-25 [2] Bioconductor
# sp                   * 2.1-1      2023-10-16 [1] CRAN (R 4.3.1)
# spam                   2.10-0     2023-10-23 [1] CRAN (R 4.3.1)
# sparseMatrixStats      1.12.2     2023-07-02 [2] Bioconductor
# spatstat.data          3.0-3      2023-10-24 [1] CRAN (R 4.3.1)
# spatstat.explore       3.2-5      2023-10-22 [1] CRAN (R 4.3.1)
# spatstat.geom          3.2-7      2023-10-20 [1] CRAN (R 4.3.1)
# spatstat.random        3.2-1      2023-10-21 [1] CRAN (R 4.3.1)
# spatstat.sparse        3.0-3      2023-10-24 [1] CRAN (R 4.3.1)
# spatstat.utils         3.0-4      2023-10-24 [1] CRAN (R 4.3.1)
# stringi                1.8.1      2023-11-13 [1] CRAN (R 4.3.1)
# stringr              * 1.5.1      2023-11-14 [1] CRAN (R 4.3.1)
# SummarizedExperiment * 1.30.2     2023-06-06 [2] Bioconductor
# survival               3.5-7      2023-08-14 [3] CRAN (R 4.3.1)
# tensor                 1.5        2012-05-05 [1] CRAN (R 4.3.1)
# tibble               * 3.2.1      2023-03-20 [2] CRAN (R 4.3.1)
# tidyr                * 1.3.0      2023-01-24 [2] CRAN (R 4.3.1)
# tidyselect             1.2.0      2022-10-10 [2] CRAN (R 4.3.1)
# tidyverse            * 2.0.0      2023-02-22 [2] CRAN (R 4.3.1)
# timechange             0.2.0      2023-01-11 [2] CRAN (R 4.3.1)
# tzdb                   0.4.0      2023-05-12 [2] CRAN (R 4.3.1)
# utf8                   1.2.4      2023-10-22 [1] CRAN (R 4.3.1)
# uwot                   0.1.16     2023-06-29 [2] CRAN (R 4.3.1)
# vctrs                  0.6.4      2023-10-12 [1] CRAN (R 4.3.1)
# viridisLite            0.4.2      2023-05-02 [2] CRAN (R 4.3.1)
# withr                  2.5.2      2023-10-30 [1] CRAN (R 4.3.1)
# xtable                 1.8-4      2019-04-21 [2] CRAN (R 4.3.1)
# XVector                0.40.0     2023-04-25 [2] Bioconductor
# zlibbioc               1.46.0     2023-04-25 [2] Bioconductor
# zoo                    1.8-12     2023-04-13 [2] CRAN (R 4.3.1)
# 
# [1] /users/csoto/R/4.3
# [2] /jhpce/shared/community/core/conda_R/4.3/R/lib64/R/site-library
# [3] /jhpce/shared/community/core/conda_R/4.3/R/lib64/R/library